### ISSUE TITLE
parallelMap leads to multiple R processes running without CPU activity

### ISSUE THREAD

**Issue by annette987** [mlr-org/parallelMap#72] opened 2019-09-04 10:37 UTC
I am experiencing a problem with parallelMap where under certain circumstances the parallel R processes do not finish and sit idle with no CPU activity. I have described the problem here: https://stackoverflow.com/questions/57784479/silent-crash-only-when-using-parallelmap-in-mlr but please note the edit at the end as I discovered the processes were not crashing after all. 

Here is another similar issue: https://github.com/wlandau/drake-examples/issues/33 

I also cannot run XGBoost with parallelMap or the R processes hang in the same way. Here is another person experiencing a similar problem: https://stackoverflow.com/questions/55978153/r-how-to-use-parallelmap-with-mlr-xgboost-on-linux-server-unexpected-perfor

All of my R packages are up to date. If I run any of my scripts without parallelMap they finish without any problem. I can provide more detailed code if necessary.

**Comment by pat-s** [comment] 2019-09-04 12:34
Can you try `parallelStart(mode = "socket")` and see if that helps?

**Comment by annette987** [comment] 2019-09-05 03:02
Yes it works with mode = "socket"! Thanks for the workaround. I tried running the 12 learners using 2 x 2-fold CV initially and that worked fine. Then I increased it to 5x5-fold CV and again it ran to completion without any problems and cleaned up at the end - no idle R processes left hanging around. 

I set cpus=12 as I am working on a machine with 12 cores:
`	parallelStart(mode="socket", cpus=12, level="mlr.resample", show.info = TRUE, logging=TRUE, storagedir='/home/annette/Experiments/Logs_new')`
and I did notice that there could be up to 18 R processes running at once. Is this a problem?

Then I tried to run xgboost. I have written a custom learner to run xgboost on survival data (yes I will do a PR soon). This used to work (probably without parallelization) but despite sourcing the code in the main file where I call parallelStart, it seems the forked processes were not able to find the code as I found the following error message repeatedly in the logs:
```
Warning in train(.learner$next.learner, transformed$data) :
  Could not train learner xgboost: Error in UseMethod("trainLearner") : 
  no applicable method for 'trainLearner' applied to an object of class "c('surv.xgboost', 'RLearnerSurv', 'RLearner', 'Learner')"
```
Should the forked processes be able to find that code?

**Comment by pat-s** [comment] 2019-09-05 06:20
Thanks for trying! Seems there is really a problem with the "multicore" mode. We need to check what and if we can do something on our side.

> it seems the forked processes were not able to find the code as I found the following error message repeatedly in the logs:

I'm not an expert in this mode but afaik you can/need to export custom functions via some options in socket mode so that the slaves are aware of it.

**Comment by pat-s** [comment] 2019-09-06 09:11
I got a reprex: https://gist.github.com/pat-s/87987bd748384668b6be45cb75c0d682

Some information to it:
I ran this reprex 10 times on my local machine with the following results:

```
1: ok
2: fail
3: ok
4: ok
5: ok
6: fail
7: ok
8: fail
9: ok
10: fail

fail: 4
ok: 6
```

"fail" means that the error described in this issue occured; i.e. no CPU activity anymore at a random point throughout the benchmark calls.

Using `mode = "socket"` I encountered no issues so far. However, this mode sometimes leave zombie processes behind even when using `parallelStop()`.

Could someone please do the same on their machine to see have some more evidence on this one?

(Sidenote: I ran a similar example with mlr3 (not exactly the same one, so not really comparable) without issues. But I only did one run so far.)

**Comment by berndbischl** [comment] 2019-09-06 10:32
thnaks a lot for the example!

my problem: as you can see, when you look into the internal pm code: we dont "do" much in terms of multicore. we call mclapply. thats its.

so i have a hard time understanding where a fixable bug on our could be?

**Comment by berndbischl** [comment] 2019-09-06 10:34
> 1: ok
> 2: fail
> 3: ok
> 4: ok
> 5: ok
> 6: fail
> 7: ok
> 8: fail
> 9: ok
> 10: fail

is this a random pattern if you rerun? or you always fail in the same lines?

**Comment by pat-s** [comment] 2019-09-06 10:40
We might take a look what the future pkg does differently to the multicore mode (if it does). Haven't had issues there yet.

Pattern: idk, just did it once. Since you have to terminate manually in between its a bit tedious. Can you try it and post your pattern?

**Comment by berndbischl** [comment] 2019-09-06 10:43
in the next 10-20 days i cannot debug this at all. i can answer here, but i am totally swamped.
holidays + other work :(

**Comment by mllg** [comment] 2019-09-06 20:57
> my problem: as you can see, when you look into the internal pm code: we dont "do" much in terms of multicore. we call mclapply. thats its.

We set `mc.preschedule = TRUE`, default is `FALSE`. Furthermore, we wrap the function call in `slaveWrapper()` where you can find some comments about crashing processes related to `sink()`. There also is a bug (but probably unrelated): https://github.com/berndbischl/parallelMap/blob/master/R/parallelMap.R#L254 should have `add = TRUE`, otherwise the previous `on.exit()` handler gets overwritten.

**Comment by pat-s** [comment] 2019-09-07 09:18
> We set mc.preschedule = TRUE, default is FALSE

Default is `TRUE`. I tested both settings, no difference.

Adding to my test above: Unfortunately I ran the tests in RStudio, which is not recommended because it [does not support forking](https://github.com/rstudio/rstudio/issues/2597). 	
When running it in the terminal I see no errors :/
So probably the errors reported above are related to RStudio.

However, my initial problems were coming from the terminal on a CentOS HPC. 
Next try: Replace `mclapply()` in `parallelMap` with `future_lapply()` and run directly on the HPC in `multicore` mode and see if that helps.

**Comment by pat-s** [comment] 2019-09-07 10:10
@annette987 	Can you try using `pat-s/parallelMap@future` (`remotes::install_github("pat-s/parallelMap@future")` and adding the following line before the `parallelStart()` call:

```r
future::plan(multicore, <number of workers>)
```

replacing `<number of workers>` with the number you usually set for `parallelStart(cpus = )`.

**Comment by pat-s** [comment] 2019-09-07 17:40
@annette987
Can you post the output of `sessionInfo()` here?
I want to check whether a custom BLAS library could be a the issue.

**Comment by annette987** [comment] 2019-09-08 01:12
Sure, here it is:
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2

**Comment by pat-s** [comment] 2019-09-08 10:28
Thanks. So you're using the atlas BLAS library. I do not have any exp with this one but still I don't think that the BLAS library should actucally responsible for that.

Just a practical hint: You may need to clean up manually after using "socket" mode sometimes as there might be zombie processes leftover if you quit the master processes manually at some point using CTRL+C or similar.

**Comment by pat-s** [comment] 2019-09-08 10:32
A short summary:

- The issue is definitely the "multicore" mode due to forking
- A workaround is to use "socket" mode
- Idk yet what exactly causes the issues
- So far everything runs fine with _mlr3_ which uses _future_ for parallelization. However, `future::future_lapply()` also just calls `mclapply()` at the very end. I'll keep on running more tests.
- The `callr` backend (pkg _future.callr_) might be a backend that overcomes the limitations of forking (_multicore_) and the problems of "socket" mode (ports cannot be opened, slow). However, this is only possible in _mlr3_. 
- I tried for a few hours porting future parallelism to _mlr_. While this is easy for the outer paralleization (`resample()`) it becomes a pain for the tuning part. We should just leave it as it is and mention the limitations somewhere.

**Comment by berndbischl** [comment] 2019-09-08 14:22
can someone now reproduce the errors when running the example without rstudio?

**Comment by pat-s** [comment] 2019-09-16 09:11
Not right now, I don't think I can tackle this in more depth until mid October.

**Comment by pat-s** [comment] 2019-09-21 08:37
@annette987 Are you running your code on a HPC or using _drake_? I only face the issues in these circumstances. 

See also the cross-ref linked above this comment for a reprex.

**Comment by annette987** [comment] 2019-09-22 07:59
I am not using drake. I am running on a HPC with 12 cpus - x86_64 architecture.
Let me know what else you need me to do.

**Comment by pat-s** [comment] 2019-09-22 08:11
Can you post a reprex of your BM study? I suspect it could have to do with multiple `parallelStart()` calls.

I could solve my HPC problems in conjunction with _drake_ but never was able to reproduce it without. 
I could test your reprex on my HPC and see if I can find something.
Thanks :)

**Comment by annette987** [comment] 2019-09-23 07:17
I'm sorry but I haven't been able to reproduce the problem. I have tried everything that caused it before and more. I don't understand it. If it comes up again I will let you know.

**Comment by pat-s** [comment] 2019-12-18 17:36
It is hard to come up with a reproducible example and it is likely that it might also be related to some OS specs. Closing here for now.

**Closed by pat-s** 2019-12-18 17:36 UTC
